import Head from 'next/head'
import Home from '../components/layout/home.jsx';
import Companies from '../components/layout/companies.jsx';
import Menu from '../components/products/menuwrapper';
import Booking from '../components/layout/booking.jsx';
import Carouser from '../components/carousel/carouserwrapper.jsx';
import Footer from '../components/layout/footer.jsx';

export default function index() {
  return (
    <div className="h-96">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home/>
      <Companies/>
      <Menu/>
      <Booking/>
      <Carouser/>
      <Footer/>
    </div>
  )
}
